project:
  type: website
  output-dir: docs
  render:
    - main.qmd

website:
  title: "Meta-eukomic"
  navbar:
    left:
      - href: main.qmd
        text: Main
        
execute:
  eval: false

format:
  html:
    theme: lux
    code-fold: show
    code-tools: true
    code-line-numbers: true
    code-block-background: true
    code-overflow: scroll
    code-block-border-left: "#ae017e"
    code-copy: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 2


